etcd:
  # Disable persistence as some k8s deployments do not have default StorageClasses
  # enabled, so this always works™. Absolutely a terrible idea in production.
  persistence:
    enabled: false
  # Not a good idea in production.
  auth:
    rbac:
      enabled: false
  statefulset:
    replicaCount: 2
  envVarsConfigMap: "etcd-env-vars"
csi:
  image:
    repo: "quay.io/piraeusdatastore"
    name: "piraeus-csi"
    version: "v0.7.3"
operator:
  nodeSet:
    spec:
      disableDRBDKernelModuleInjection: false
  image:
    repo: "woojay"
    name: "piraeus-dont"
    version: "experimental3"


